import test from 'node:test';
import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import {seal,unseal,allowedPath,challenge} from '../hosted/security.mjs';
import {GitHubWorkspace,BRANCH,STATE} from '../hosted/github.mjs';
test('encrypted sessions reject tampering, expiration and cross-purpose reuse',()=>{const key=randomBytes(32).toString('hex');const payload={purpose:'session',exp:Date.now()+60000,token:'private-test-token'};const value=seal(payload,key);assert.ok(!value.includes(payload.token));assert.deepEqual(unseal(value,key,'session'),payload);assert.throws(()=>unseal(value.slice(0,-8)+'tampered',key,'session'));assert.throws(()=>unseal(value,key,'oauth'));assert.throws(()=>unseal(seal({...payload,exp:1},key),key,'session'));assert.equal(challenge('test').length,43);assert.equal(allowedPath('pairs/dirk-chris/README.md'),true);assert.equal(allowedPath('pairs/dirk-chris/../../.env'),false);assert.equal(allowedPath('.env'),false);});
function fixture(){const source='<html><style id="app-css">body{color:blue}</style><!-- APP HTML START --><h1>Move</h1><!-- APP HTML END --><script id="app-js">void 0;</script></html>';const pairs=[{id:'one-two',team:'One & Two'},{id:'three-four',team:'Three & Four'}];let head='base',branch=null,files={'workshop/starter/index.html':source,'workshop/pairs.json':JSON.stringify(pairs)},pending={},calls=[];const w=new GitHubWorkspace('test');w.api=async(path,method='GET',body)=>{calls.push({path,method,body});const end=path.replace('/repos/artur-octalysis/tog-learning','');if(end==='/git/ref/heads/main')return {object:{sha:'base'}};if(end==='/git/ref/heads/'+BRANCH){if(!branch)throw Object.assign(Error('missing'),{status:404});return {object:{sha:head}};}if(end==='/git/refs'&&method==='POST'){branch=BRANCH;return {};}
if(end.startsWith('/contents/')){const path=end.slice(10).split('?')[0];if(!(path in files))throw Object.assign(Error('missing'),{status:404});return {type:'file',encoding:'base64',content:Buffer.from(files[path]).toString('base64')};}
if(end.startsWith('/git/commits/')&&method==='GET')return {tree:{sha:'tree'}};if(end==='/git/trees'&&method==='POST'){pending=Object.fromEntries(body.tree.map(x=>[x.path,x.content]));return {sha:'next-tree'};}if(end==='/git/commits'&&method==='POST')return {sha:'commit-'+calls.length};if(end==='/git/refs/heads/'+BRANCH){Object.assign(files,pending);head=body.sha;return {};}
if(end.startsWith('/git/trees/')&&method==='GET')return {tree:Object.keys(files).map(path=>({type:'blob',path}))};if(end.startsWith('/pulls?'))return [];if(end==='/pulls'&&method==='POST')return {html_url:'https://github.com/example/pr/1'};throw Error('Unexpected '+method+' '+end);};return {w,files,calls};}
test('hosted steps commit real HTML progressively and distribute exact copies atomically',async()=>{const {w,files,calls}=fixture();await assert.rejects(w.build(1),/order/);await w.build(0);assert.ok(!files['workshop/live/index.html'].includes('body{color:blue}'));await w.build(1);assert.ok(files['workshop/live/index.html'].includes('body{color:blue}'));await w.build(2);assert.ok(files['workshop/live/index.html'].includes('void 0;'));const count=calls.length;await w.build(2);assert.ok(calls.slice(count).every(call=>call.method==='GET'));await w.publish();assert.equal(files['pairs/one-two/index.html'],files['workshop/live/index.html']);assert.equal(files['pairs/three-four/index.html'],files['workshop/live/index.html']);assert.equal(JSON.parse(files[STATE]).distributed,true);const updates=calls.filter(x=>x.method==='PATCH');assert.ok(updates.every(x=>x.body.force===false));});
test('hosted distribution refuses existing pair work before any write',async()=>{const {w,files,calls}=fixture();await w.build(0);await w.build(1);await w.build(2);files['pairs/three-four/index.html']='Participant work';const before=calls.length;await assert.rejects(w.publish(),/already exists/);assert.equal(files['pairs/three-four/index.html'],'Participant work');assert.equal(files['pairs/one-two/index.html'],undefined);assert.ok(calls.slice(before).every(call=>call.method==='GET'));});
test('merge is pinned to the validated pull request head',async()=>{const {w}=fixture();let merged=null;w.pulls=async()=>[{number:1,state:'open',html_url:'https://example.test/pr'}];w.snapshot=async()=>({stage:3});w.api=async(path,method,body)=>{if(path.endsWith('/pulls/1'))return {mergeable:true,head:{sha:'validated-head'}};if(path.endsWith('/check-runs'))return {check_runs:[{name:'Validate and build',status:'completed',conclusion:'success'}]};if(path.endsWith('/status'))return {total_count:0};if(path.endsWith('/merge')){merged=body;return {merged:true};}throw Error(path);};assert.equal((await w.progress()).stage,3);assert.equal(merged.sha,'validated-head');});
