import {seal,unseal,random,challenge} from '../hosted/security.mjs';
import {GitHubWorkspace} from '../hosted/github.mjs';
const frontend='https://artur-octalysis.github.io';
const appOrigin='https://html-workshop-api.vercel.app';
const origins=new Set([frontend,appOrigin]);
const callback=appOrigin+'/api/workshop?action=callback';
const cookieName='__Host-workshop-oauth';
function headers(origin){return {'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer',...(origins.has(origin)?{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type, Authorization','Vary':'Origin'}:{})};}
function json(data,status=200,origin){return Response.json(data,{status,headers:headers(origin)});}
function config(){if(!process.env.GITHUB_CLIENT_ID||!process.env.GITHUB_CLIENT_SECRET||!process.env.SESSION_KEY)throw Object.assign(Error('GitHub sign-in setup is not complete yet.'),{status:503});return {id:process.env.GITHUB_CLIENT_ID,secret:process.env.GITHUB_CLIENT_SECRET,key:process.env.SESSION_KEY,presenter:process.env.PRESENTER_ID||'293132883'};}
function html(body,extra={}){return new Response('<!doctype html><html><head><meta charset="utf-8"><title>Workshop GitHub sign-in</title></head><body style="font:16px system-ui;padding:40px;color:#0e2a6e">'+body+'</body></html>',{headers:{'Content-Type':'text/html',...headers(),...extra}});}
export async function GET(request){const url=new URL(request.url),action=url.searchParams.get('action')||'health',origin=request.headers.get('origin')||url.origin;try{
 if(action==='health')return json({service:'workshop-github',configured:!!(process.env.GITHUB_CLIENT_ID&&process.env.GITHUB_CLIENT_SECRET&&process.env.SESSION_KEY)},200,origin);
 const cfg=config();
 if(action==='login'){const destination=url.searchParams.get('origin')||frontend,nonce=url.searchParams.get('nonce');if(!origins.has(destination)||!/^[\w-]{20,100}$/.test(nonce||''))return json({error:'Invalid sign-in request'},400,origin);const state=random(),verifier=random();const transaction=seal({purpose:'oauth',exp:Date.now()+600000,state,verifier,nonce,origin:destination},cfg.key);const authorize=new URL('https://github.com/login/oauth/authorize');Object.entries({client_id:cfg.id,redirect_uri:callback,state,code_challenge:challenge(verifier),code_challenge_method:'S256'}).forEach(([key,value])=>authorize.searchParams.set(key,value));return new Response(null,{status:302,headers:{Location:authorize.href,'Cache-Control':'no-store','Set-Cookie':cookieName+'='+transaction+'; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=600'}});}
 if(action==='callback'){const raw=(request.headers.get('cookie')||'').split(';').map(v=>v.trim()).find(v=>v.startsWith(cookieName+'='))?.slice(cookieName.length+1);const flow=unseal(raw||'',cfg.key,'oauth');if(url.searchParams.get('state')!==flow.state)throw Error('Sign-in state mismatch. Try again.');if(url.searchParams.get('error'))throw Error('GitHub authorization was not completed.');const response=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:cfg.id,client_secret:cfg.secret,code:url.searchParams.get('code'),redirect_uri:callback,code_verifier:flow.verifier})});const auth=await response.json();if(!response.ok||!auth.access_token)throw Error('GitHub could not complete sign-in. Try again.');const workspace=new GitHubWorkspace(auth.access_token);const user=await workspace.authorize(cfg.presenter);const session=seal({purpose:'session',exp:Date.now()+2*60*60*1000,token:auth.access_token,id:user.id,login:user.login},cfg.key);const payload=JSON.stringify({type:'workshop-signin',nonce:flow.nonce,session,user}).replaceAll('<','\\u003c');const scriptNonce=random();return html('<h1>Signed in.</h1><p>You can return to the workshop.</p><script nonce="'+scriptNonce+'">if(window.opener){window.opener.postMessage('+payload+','+JSON.stringify(flow.origin)+');window.close();}</script>',{'Set-Cookie':cookieName+'=; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=0','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-"+scriptNonce+"'; frame-ancestors 'none'"});}
 if(!origins.has(origin))return json({error:'Origin not allowed'},403,origin);const session=unseal((request.headers.get('authorization')||'').replace(/^Bearer /,''),cfg.key,'session');if(String(session.id)!==cfg.presenter)return json({error:'Presenter access required'},403,origin);const workspace=new GitHubWorkspace(session.token);
 if(action==='session'){const user=await workspace.authorize(cfg.presenter);return json({...await workspace.snapshot(),user},200,origin);}
 if(action==='tree')return json(await workspace.snapshot(),200,origin);
 if(action==='file')return new Response(await workspace.read(url.searchParams.get('path')),{headers:{...headers(origin),'Content-Type':'text/plain; charset=utf-8'}});
 return json({error:'Unknown operation'},404,origin);
 }catch(error){if(action==='callback')return html('<h1>Sign-in needs attention.</h1><p>'+String(error.message).replaceAll('&','&amp;').replaceAll('<','&lt;')+'</p>');return json({error:error.message},[400,401,403,404,409,503].includes(error.status)?error.status:400,origin);}}
export async function POST(request){const origin=request.headers.get('origin');if(!origins.has(origin)||!request.headers.get('content-type')?.startsWith('application/json'))return json({error:'Origin not allowed'},403,origin);try{const cfg=config();const session=unseal((request.headers.get('authorization')||'').replace(/^Bearer /,''),cfg.key,'session');const workspace=new GitHubWorkspace(session.token);await workspace.authorize(cfg.presenter);const action=new URL(request.url).searchParams.get('action');const raw=await request.text();if(raw.length>1024)return json({error:'Request too large'},413,origin);const data=JSON.parse(raw||'{}');if(action==='build')return json(await workspace.build(data.stage),200,origin);if(action==='publish')return json(await workspace.publish(),202,origin);if(action==='progress')return json(await workspace.progress(),200,origin);if(action==='logout'){await fetch('https://api.github.com/applications/'+cfg.id+'/token',{method:'DELETE',headers:{Authorization:'Basic '+Buffer.from(cfg.id+':'+cfg.secret).toString('base64'),Accept:'application/vnd.github+json','Content-Type':'application/json'},body:JSON.stringify({access_token:session.token})});return json({signedOut:true},200,origin);}return json({error:'Unknown operation'},404,origin);}catch(error){return json({error:error.message},[400,401,403,404,409,503].includes(error.status)?error.status:400,origin);}}
export function OPTIONS(request){const origin=request.headers.get('origin');return new Response(null,{status:origins.has(origin)?204:403,headers:headers(origin)});}
