import {buildDocument} from '../site/assets/chat-build-model.js';
import {allowedPath} from './security.mjs';
export const REPO='artur-octalysis/html-the-new-english';
export const BRANCH='workshop/hosted-presenter';
export const STATE='workshop/live/session.json';
const root='/repos/'+REPO;
export class GitHubWorkspace{
 constructor(token,request=fetch){this.token=token;this.request=request;}
 async api(path,method='GET',body){const response=await this.request('https://api.github.com'+path,{method,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+this.token,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await response.json().catch(()=>({}));if(!response.ok){const error=Error(data.message||'GitHub could not complete this operation.');error.status=response.status;throw error;}return data;}
 async authorize(id){const user=await this.api('/user');if(String(user.id)!==String(id))throw Object.assign(Error('Only the workshop presenter can change repository files.'),{status:403});const repo=await this.api(root);if(!repo.permissions?.push)throw Object.assign(Error('Install the workshop GitHub App on html-the-new-english and grant repository access.'),{status:403});return {id:user.id,login:user.login};}
 async ref(branch){try{return (await this.api(root+'/git/ref/heads/'+branch)).object.sha;}catch(error){if(error.status===404)return null;throw error;}}
 async content(path,ref=BRANCH){try{const data=await this.api(root+'/contents/'+path+'?ref='+encodeURIComponent(ref));if(data.type!=='file'||data.encoding!=='base64')throw Error('This is not a readable text file.');return Buffer.from(data.content,'base64').toString();}catch(error){if(error.status===404)return null;throw error;}}
 async state(){const head=await this.ref(BRANCH);if(!head)return {head:null,stage:-1};const raw=await this.content(STATE,head);return {head,...(raw?JSON.parse(raw):{stage:-1})};}
 async commit(files,message,head){const commit=await this.api(root+'/git/commits/'+head);const tree=await this.api(root+'/git/trees','POST',{base_tree:commit.tree.sha,tree:Object.entries(files).map(([path,content])=>({path,mode:'100644',type:'blob',content}))});const next=await this.api(root+'/git/commits','POST',{message,tree:tree.sha,parents:[head]});try{await this.api(root+'/git/refs/heads/'+BRANCH,'PATCH',{sha:next.sha,force:false});}catch(error){if(error.status===422)throw Object.assign(Error('The repository changed during this action. Try again to use the latest version.'),{status:409});throw error;}return next.sha;}
 async build(stage){if(!Number.isInteger(stage)||stage<0||stage>2)throw Error('Invalid build step.');let state=await this.state();if(stage===state.stage)return this.snapshot();if(stage!==state.stage+1)throw Object.assign(Error('Run the prompts in order.'),{status:409});if(!state.head){const main=await this.ref('main');await this.api(root+'/git/refs','POST',{ref:'refs/heads/'+BRANCH,sha:main});state={head:main,stage:-1};}
 const source=await this.content('workshop/starter/index.html',state.head);const sources={html:source?.match(/<!-- APP HTML START -->([\s\S]*?)<!-- APP HTML END -->/)?.[1]?.trim(),css:source?.match(/<style id="app-css">([\s\S]*?)<\/style>/)?.[1]?.trim(),js:source?.match(/<script id="app-js">([\s\S]*?)<\/script>/)?.[1]?.trim()};if(Object.values(sources).some(value=>!value))throw Error('The starter source is incomplete.');
 await this.commit({'workshop/live/index.html':buildDocument(sources,stage),[STATE]:JSON.stringify({stage,distributed:false})+'\n'},['Create HTML screen','Add CSS to the fitness screen','Apply JavaScript interaction'][stage],state.head);return this.snapshot();}
 async pulls(){return this.api(root+'/pulls?state=all&head=artur-octalysis:'+encodeURIComponent(BRANCH)+'&base=main&per_page=10');}
 async publish(){let state=await this.state();if(state.stage!==2)throw Object.assign(Error('Finish HTML, CSS and JavaScript first.'),{status:409});const existing=(await this.pulls()).find(pr=>pr.state==='open'||pr.merged_at);if(existing)return {accepted:true,pullRequest:existing.html_url};
 if(!state.distributed){const pairs=JSON.parse(await this.content('workshop/pairs.json',state.head));const main=await this.ref('main');const files={};const html=await this.content('workshop/live/index.html',state.head);
 for(const pair of pairs){if(!/^[a-z]+(?:-[a-z]+)*$/.test(pair.id))throw Error('Invalid pair folder');const path='pairs/'+pair.id+'/index.html';if(await this.content(path,state.head)!==null||await this.content(path,main)!==null)throw Object.assign(Error(path+' already exists. Existing pair work will not be overwritten.'),{status:409});files[path]=html;}
 files['workshop/starter/index.html']=html;files[STATE]=JSON.stringify({stage:2,distributed:true})+'\n';await this.commit(files,'Copy the finished screen into all five pair folders',state.head);}
 const pr=await this.api(root+'/pulls','POST',{title:'Distribute the live workshop screen',head:BRANCH,base:'main',body:'Created through the signed-in public workshop. Copies the completed fitness screen into all five pair folders. Existing pair work was checked before copying. Automated validation must pass before the workshop merges this handout.'});return {accepted:true,pullRequest:pr.html_url};}
 async progress(){const pr=(await this.pulls()).find(pr=>pr.state==='open'||pr.merged_at);if(!pr)return {busy:false,error:'No handout pull request was found.'};if(pr.merged_at)return this.snapshot();const detail=await this.api(root+'/pulls/'+pr.number);if(detail.mergeable===false)return {busy:false,error:'The handout conflicts with main. Review '+pr.html_url+' before merging.',pullRequest:pr.html_url};
 const checks=(await this.api(root+'/commits/'+detail.head.sha+'/check-runs')).check_runs||[];const required=checks.filter(check=>check.name==='Validate and build');if(!required.length||required.some(check=>check.status!=='completed'))return {busy:true,message:'GitHub is validating the handout…',pullRequest:pr.html_url};if(required.some(check=>check.conclusion!=='success'))return {busy:false,error:'GitHub validation failed. Review '+pr.html_url,pullRequest:pr.html_url};
 const statuses=await this.api(root+'/commits/'+detail.head.sha+'/status');if(statuses.total_count&&statuses.state!=='success')return {busy:true,message:'Waiting for commit checks…',pullRequest:pr.html_url};
 await this.api(root+'/pulls/'+pr.number+'/merge','PUT',{merge_method:'squash',sha:detail.head.sha});return this.snapshot();}
 async snapshot(){const state=await this.state();let pr=null;if(state.distributed)pr=(await this.pulls()).find(pr=>pr.state==='open'||pr.merged_at);const merged=!!pr?.merged_at;const ref=merged?'main':state.head||'main';const pairs=JSON.parse(await this.content('workshop/pairs.json',ref));const head=await this.ref(ref==='main'?'main':BRANCH);const tree=await this.api(root+'/git/trees/'+head+'?recursive=1');if(tree.truncated)throw Error('Repository file tree is too large.');return {mode:'hosted',pairs:pairs.map(pair=>({...pair,files:tree.tree.filter(file=>file.type==='blob'&&file.path.startsWith('pairs/'+pair.id+'/')).map(file=>file.path)})),stage:merged?3:state.stage,busy:!!pr&&!merged&&pr.state==='open',message:merged?'Merged into main. GitHub Pages is publishing.':pr?'GitHub is validating the handout…':'',result:merged?{pullRequest:pr.html_url}:null,branch:merged?'main':BRANCH,liveFiles:state.stage>=0?['workshop/live/index.html']:[]};}
 async read(path){if(!allowedPath(path))throw Object.assign(Error('File is outside the workshop folders.'),{status:403});const state=await this.state();let ref=state.head||'main';if(state.distributed&&(await this.pulls()).some(pr=>pr.merged_at))ref='main';const content=await this.content(path,ref);if(content===null)throw Object.assign(Error('File not found.'),{status:404});return content;}
}
